import re
import streamlit as st

def clean_markdown_response(text: str) -> str:
    if not text:
        return ""
    # Remove [svg](...) markdown anchor links generated by LLMs
    cleaned = re.sub(r'\[svg\]\([^)]*\)', '', text)
    cleaned = re.sub(r'\[#\]\([^)]*\)', '', cleaned)
    cleaned = re.sub(r'\n{3,}', '\n\n', cleaned)
    return cleaned.strip()

class LLMService:
    def __init__(self, model_name: str = "gemini-1.5-flash"):
        self.model_name = model_name

    def _get_api_key(self) -> str | None:
        try:
            if "GOOGLE_API_KEY" in st.secrets:
                raw_key = str(st.secrets["GOOGLE_API_KEY"])
                key = raw_key.strip().strip('"').strip("'")
                if key:
                    return key
        except Exception:
            pass
        return None

    def _extract_text(self, response) -> str | None:
        if not response:
            return None
        raw_text = None
        try:
            if hasattr(response, "text") and response.text:
                raw_text = response.text.strip()
        except Exception:
            pass

        if not raw_text:
            try:
                if hasattr(response, "candidates") and response.candidates:
                    for cand in response.candidates:
                        if hasattr(cand, "content") and hasattr(cand.content, "parts"):
                            parts = [p.text for p in cand.content.parts if hasattr(p, "text") and p.text]
                            if parts:
                                raw_text = "".join(parts).strip()
                                break
            except Exception:
                pass

        if raw_text:
            return clean_markdown_response(raw_text)
        return None

    def generate_response(self, prompt: str = "", context: str | None = None, **kwargs) -> str:
        if not prompt and "query" in kwargs:
            prompt = kwargs["query"]

        api_key = self._get_api_key()
        if not api_key:
            return "API key not configured"

        if context and context.strip():
            full_prompt = (
                f"You are a helpful AI assistant. Use the following context to answer the user's question accurately.\n\n"
                f"--- CONTEXT ---\n{context}\n---------------\n\n"
                f"Question: {prompt}\n\nAnswer:"
            )
        else:
            full_prompt = prompt

        errors = []

        # 1. Primary: Try modern google-genai SDK
        try:
            from google import genai
            client = genai.Client(api_key=api_key)
            
            available_models = []
            try:
                for m in client.models.list():
                    name = getattr(m, "name", "") or str(m)
                    clean_name = name.replace("models/", "").lower()
                    if "gemini" in clean_name and not any(bad in clean_name for bad in ["embed", "imagen", "tts", "audio"]):
                        available_models.append(clean_name)
            except Exception as list_err:
                errors.append(f"genai_list: {str(list_err)}")

            candidates = [self.model_name, "gemini-1.5-flash", "gemini-2.0-flash", "gemini-2.5-flash", "gemini-1.5-pro"]
            for m in available_models:
                if m not in candidates:
                    candidates.append(m)

            for m in candidates:
                try:
                    response = client.models.generate_content(
                        model=m,
                        contents=full_prompt,
                    )
                    text = self._extract_text(response)
                    if text:
                        return text
                except Exception as inner_e:
                    err_msg = str(inner_e)
                    errors.append(f"genai({m}): {err_msg}")
                    err_text = err_msg.lower()
                    if any(k in err_text for k in ["404", "not found", "modalities", "audio", "tts", "invalid_argument"]):
                        continue
                    if "api_key_invalid" in err_text or "unauthenticated" in err_text:
                        return f"API Key Error: {err_msg}"
                    continue
        except Exception as e1:
            errors.append(f"genai_init: {str(e1)}")

        # 2. Backup: Try legacy google-generativeai SDK
        try:
            import google.generativeai as legacy_genai
            legacy_genai.configure(api_key=api_key)
            
            legacy_available = []
            try:
                for m in legacy_genai.list_models():
                    if hasattr(m, "supported_generation_methods") and "generateContent" in m.supported_generation_methods:
                        c_name = m.name.replace("models/", "").lower()
                        if not any(bad in c_name for bad in ["embed", "imagen", "tts", "audio", "pro-001"]):
                            legacy_available.append(c_name)
            except Exception as legacy_list_err:
                errors.append(f"legacy_list: {str(legacy_list_err)}")

            candidates_legacy = [self.model_name, "gemini-1.5-flash", "gemini-1.5-flash-latest"]
            for m in legacy_available:
                if m not in candidates_legacy:
                    candidates_legacy.append(m)

            for m in candidates_legacy:
                try:
                    model = legacy_genai.GenerativeModel(m)
                    res = model.generate_content(full_prompt)
                    text = self._extract_text(res)
                    if text:
                        return text
                except Exception as inner_e:
                    errors.append(f"legacy({m}): {str(inner_e)}")
                    continue
        except Exception as e2:
            errors.append(f"legacy_init: {str(e2)}")

        if errors:
            for err in reversed(errors):
                if "api_key_invalid" in err.lower() or "unauthenticated" in err.lower():
                    return f"API Key Error: {err}"
            return f"AI service error: {errors[-1]}"

        return "AI service temporarily unavailable"

    def generate_general_response(self, prompt: str) -> str:
        return self.generate_response(prompt=prompt, context=None)
